"""changed datetime

Revision ID: 3f7f036fc2d2
Revises: b7ecc89aa603
Create Date: 2023-07-23 13:59:37.826741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7f036fc2d2'
down_revision = 'b7ecc89aa603'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
